name: Flutter Web Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'flutter/web/**'
      - 'flutter/lib/web/**'
      - '.github/workflows/flutter-web.yml'

permissions:
  contents: read

jobs:
  build-web:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ""